@startuml
title Query I-Score

participant "ICON Service engine" as IS
participant "IISS engine" as IISS
database "state DB" as SDB
database "IISS data" as ID
participant "Reward Calculator" as RC
database "I-Score DB" as ISDB

-> IS: [mq] query
IS -> IISS: [call] query
IISS -> RC: [IPC] query
RC -> ISDB: read I-Score
RC -> IISS: [IPC] query response
IISS -> IS: return response

newpage Claim I-Score

group block invoke

-> IS: [mq] block invoke
IS -> IISS: [call] with TX
IISS -> RC: [IPC] claim
RC -> ISDB: read I-Score
opt old I-Score
RC -> RC: caculate I-Score
end
RC -> IISS: claim response
IISS -> IS: return response

end

group write_precommit_state, remove_precommit_state

-> IS: [mq] write_precommit_state\nor remove_precommit_state
IS -> IISS: commit or rollback
alt commit
IISS -> SDB: update ICX
IISS -> ID: write claim TX
IISS -> RC: [IPC] commit_block with success
RC -> ISDB: write I-Score to snapshot
else remove
IISS -> RC: [IPC] commit_block with failure
RC -> RC: remove I-Score
end

end

@enduml
